package com.interviewcoach.agent.entity;

public enum CoachEvent {
    TARGET_CREATED,
    RESUME_SUMMARY_CONFIRMED,
    ASSESSMENT_COMPLETED,
    TRAINING_TASK_COMPLETED,
    TRAINING_SESSION_COMPLETED,
    MOCK_INTERVIEW_COMPLETED,
    MEMORY_CORRECTED,
    APP_SESSION_STARTED
}
